version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: temu_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: temu/backend:latest
    restart: always
    depends_on:
      - db
    environment:
      # Damit Nest/TypeORM zur Laufzeit die DB findet:
      DB_HOST: db
      DB_PORT: '5432'
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_DATABASE: temu_db
    ports:
      - '3001:3001'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: temu/frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      # Next.js kommuniziert intern mit dem Backend-Service
      NEXT_PUBLIC_API_BASE_URL: http://backend:3001
    ports:
      - '3000:3000'

volumes:
  db_data:
