version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER:   user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB:     temu_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  db_data:
