version: '3.8'
services:
  backend:
    build:
      context: ./backend
      target: builder   # oder ganz normal, je nach Dockerfile
    volumes:
      - ./backend:/app   # Quellcode reinkippen
      - /app/node_modules  # node_modules aus dem Image beibehalten
    ports:
      - '3001:3001'
    command: npm run start:dev  # NestJS Watch-Mode

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: npm run dev         # Next.js Dev-Server
