apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: plirexic/temu-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "user"
        - name: DB_PASSWORD
          value: "pass"
        - name: DB_DATABASE
          value: "temu_db"
